#!/bin/bash

cd /home/wford/NuclearSim/DoppBroadParrallel/

rm -rf CMakeCache.txt CMakeFiles

if [ "$1" = "" ]; then
	cmake -DTOPC_USE=1 -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_BUILD_TYPE=Release ./
	make clean
	make -j4
	echo "No Input File Given"
	
elif [ "$1" = "gdb" ]; then
	if [ "$2" = "para" ]; then
		cmake -DTOPC_USE=1 -DTOPC_USE_SEQ=0 -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_BUILD_TYPE=Debug ./
		make clean
		make -j4
		gdb ./dopplerbroadpara
	else
		cmake -DTOPC_USE=1 -DTOPC_USE_SEQ=1 -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_BUILD_TYPE=Debug ./
		make clean
		make -j4
		gdb ./dopplerbroadpara
	fi
else
	cmake -DTOPC_USE=1 -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_BUILD_TYPE=Release ./
	make clean
	make -j4
	./dopplerbroadpara $1 $2 $3 $4 $5 $6
fi
